# Generated by Django 6.0.5 on 2026-05-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='topic',
            field=models.CharField(choices=[('accounting', 'Accounting'), ('agriculture', 'Agriculture'), ('algorithms', 'Algorithms'), ('anatomy', 'Anatomy'), ('arts', 'Arts'), ('biochemistry', 'Biochemistry'), ('biology', 'Biology'), ('business', 'Business'), ('chemistry', 'Chemistry'), ('circuits', 'Circuits'), ('communications', 'Communications'), ('control', 'Control'), ('dentistry', 'Dentistry'), ('design', 'Design'), ('drawing', 'Drawing'), ('economics', 'Economics'), ('education', 'Education'), ('electronics', 'Electronics'), ('environment', 'Environment'), ('finance', 'Finance'), ('fluid_mechanics', 'Fluid Mechanics'), ('geography', 'Geography'), ('hardware', 'Hardware'), ('history', 'History'), ('hydraulics', 'Hydraulics'), ('language', 'Language'), ('law', 'Law'), ('management', 'Management'), ('manufacturing', 'Manufacturing'), ('marketing', 'Marketing'), ('materials', 'Materials'), ('mathematics', 'Mathematics'), ('mechanics', 'Mechanics'), ('medicine', 'Medicine'), ('microbiology', 'Microbiology'), ('naval', 'Naval'), ('networks', 'Networks'), ('nuclear', 'Nuclear'), ('nursing', 'Nursing'), ('nutrition', 'Nutrition'), ('pathology', 'Pathology'), ('pharmacology', 'Pharmacology'), ('pharmacy', 'Pharmacy'), ('philosophy', 'Philosophy'), ('physics', 'Physics'), ('physiology', 'Physiology'), ('power', 'Power'), ('programming', 'Programming'), ('psychology', 'Psychology'), ('signals', 'Signals'), ('sociology', 'Sociology'), ('software', 'Software'), ('sports', 'Sports'), ('structures', 'Structures'), ('surgery', 'Surgery'), ('surveying', 'Surveying'), ('systems', 'Systems'), ('textiles', 'Textiles'), ('thermodynamics', 'Thermodynamics'), ('tourism', 'Tourism'), ('veterinary', 'Veterinary')], default='other', max_length=50),
        ),
    ]
