/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/advisor.styles` | `/advisor.styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/advisor` | `/advisor`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index.styles` | `/index.styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/theme` | `/theme`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/advisor.styles` | `/advisor.styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/advisor` | `/advisor`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/index.styles` | `/index.styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/theme` | `/theme`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/advisor.styles${`?${string}` | `#${string}` | ''}` | `/advisor.styles${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/advisor${`?${string}` | `#${string}` | ''}` | `/advisor${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/index.styles${`?${string}` | `#${string}` | ''}` | `/index.styles${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/theme${`?${string}` | `#${string}` | ''}` | `/theme${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/advisor.styles` | `/advisor.styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/advisor` | `/advisor`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index.styles` | `/index.styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/theme` | `/theme`; params?: Router.UnknownInputParams; };
    }
  }
}
